
# original
#libdir='/eos/azoghbi/soft/usr/lib'
#incdir='/eos/azoghbi/soft/usr/include'
# most systems
#libdir='/home/caes/science/psdlag-agn/src/inc'
#incdir='/home/caes/science/psdlag-agn/src/inc'
# thor
libdir='/home/research/xaw5719/psdlag-agn/src/inc'
alglibdir='/home/research/xaw5719/psdlag-agn/src/inc/alglib'
incdir='/home/research/xaw5719/psdlag-agn/src/inc'
psdlag:
	g++ *cpp inc/alglib/*cpp -o psdlag -O3 -Wall -I${incdir} -L${libdir} -L${alglibdir} -I${alglibdir}
