

#libdir='/eos/azoghbi/soft/usr/lib'
#incdir='/eos/azoghbi/soft/usr/include'
libdir='/home/caes/science/psdlag-agn/src'
incdir='/home/caes/science/psdlag-agn/src/inc'


psdlag:
	g++ *cpp -o psdlag -O3 -Wall -lalglib -I${incdir} -L${libdir}
